services:
  # app:
  #   build: .
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/app

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./pg_data/:/var/lib/postgresql/data